service: node-aws-cars

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      host: localhost
      port: 8000
      noStart: true
      migrate: true
    migration:
      dir: offline/migrations
    stages:
      - dev

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    DYNAMODB_TABLE_CARS: ${self:service}-${opt:stage, self:provider.stage}-cars
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_CARS}"

functions:
  create:
    handler: lambdas/create.create
    events:
      - http:
          path: cars
          method: post
          cors: true

  list:
    handler: lambdas/list.list
    events:
      - http:
          path: cars
          method: get
          cors: true

  get:
    handler: lambdas/get.get
    events:
      - http:
          path: cars/{brand}/{model}
          method: get
          cors: true

  update:
    handler: lambdas/update.update
    events:
      - http:
          path: cars/{brand}/{model}
          method: patch
          cors: true

  delete:
    handler: lambdas/delete.delete
    events:
      - http:
          path: cars/{brand}/{model}
          method: delete
          cors: true

resources:
  Resources:
    CarsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: brand
            AttributeType: S
          -
            AttributeName: model
            AttributeType: S
        KeySchema:
          -
            AttributeName: brand
            KeyType: HASH
          -
            AttributeName: model
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE_CARS}
        
